config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :reservation_guests
  resources :promotions
  resources :events
  resources :payments
  resources :orders
  resources :suppliers
  resources :ingredients
  resources :employees
  resources :reservations
  resources :menus
  resources :restaurants do
    resources :reviews
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :restaurant
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :restaurant
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :restaurant
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :restaurant
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  has_many :reservation_guests
end

app/models/reservation_guest.rb
class ReservationGuest < ApplicationRecord
  belongs_to :reservation
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_many :menus
  has_many :reservations
  has_many :employees
  has_many :ingredients
  has_many :suppliers
  has_many :orders
  has_many :events
  has_many :promotions

  before_create :generate_uuid

  private

  def generate_uuid
    self.uuid = SecureRandom.hex(8)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity, :unit)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.label :unit, style: "display: block" %>
    <%= form.text_field :unit %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= ingredient.quantity %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= ingredient.unit %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>