config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :reservation_guests
  resources :promotions
  resources :events
  resources :payments
  resources :orders
  resources :suppliers
  resources :ingredients
  resources :employees
  resources :reservations
  resources :menus
  resources :restaurants do
    resources :reviews
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :restaurant
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :restaurant
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :restaurant
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :restaurant
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :restaurant
  has_many :reservation_guests
end

app/models/reservation_guest.rb
class ReservationGuest < ApplicationRecord
  belongs_to :reservation
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  has_many :menus
  has_many :reservations
  has_many :employees
  has_many :ingredients
  has_many :suppliers
  has_many :orders
  has_many :events
  has_many :promotions

  before_create :generate_uuid

  private

  def generate_uuid
    self.uuid = SecureRandom.hex(8)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/reservation_guests_controller.rb
class ReservationGuestsController < ApplicationController
  before_action :set_reservation_guest, only: %i[ show edit update destroy ]

  # GET /reservation_guests or /reservation_guests.json
  def index
    @reservation_guests = ReservationGuest.all
  end

  # GET /reservation_guests/1 or /reservation_guests/1.json
  def show
  end

  # GET /reservation_guests/new
  def new
    @reservation_guest = ReservationGuest.new
  end

  # GET /reservation_guests/1/edit
  def edit
  end

  # POST /reservation_guests or /reservation_guests.json
  def create
    @reservation_guest = ReservationGuest.new(reservation_guest_params)

    respond_to do |format|
      if @reservation_guest.save
        format.html { redirect_to reservation_guest_url(@reservation_guest), notice: "Reservation guest was successfully created." }
        format.json { render :show, status: :created, location: @reservation_guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservation_guests/1 or /reservation_guests/1.json
  def update
    respond_to do |format|
      if @reservation_guest.update(reservation_guest_params)
        format.html { redirect_to reservation_guest_url(@reservation_guest), notice: "Reservation guest was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation_guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservation_guests/1 or /reservation_guests/1.json
  def destroy
    @reservation_guest.destroy

    respond_to do |format|
      format.html { redirect_to reservation_guests_url, notice: "Reservation guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation_guest
      @reservation_guest = ReservationGuest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_guest_params
      params.require(:reservation_guest).permit(:reservation_id, :guest_name, :contact_number, :email)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/helpers/reservation_guests_helper.rb
module ReservationGuestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/reservation_guests/_form.html.erb
<%= form_with(model: reservation_guest) do |form| %>
  <% if reservation_guest.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation_guest.errors.count, "error") %> prohibited this reservation_guest from being saved:</h2>

      <ul>
        <% reservation_guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :reservation_id, style: "display: block" %>
    <%= form.text_field :reservation_id %>
  </div>

  <div>
    <%= form.label :guest_name, style: "display: block" %>
    <%= form.text_field :guest_name %>
  </div>

  <div>
    <%= form.label :contact_number, style: "display: block" %>
    <%= form.text_field :contact_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservation_guests/_reservation_guest.html.erb
<div id="<%= dom_id reservation_guest %>">
  <p>
    <strong>Reservation:</strong>
    <%= reservation_guest.reservation_id %>
  </p>

  <p>
    <strong>Guest name:</strong>
    <%= reservation_guest.guest_name %>
  </p>

  <p>
    <strong>Contact number:</strong>
    <%= reservation_guest.contact_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= reservation_guest.email %>
  </p>

</div>

app/views/reservation_guests/edit.html.erb
<h1>Editing reservation guest</h1>

<%= render "form", reservation_guest: @reservation_guest %>

<br>

<div>
  <%= link_to "Show this reservation guest", @reservation_guest %> |
  <%= link_to "Back to reservation guests", reservation_guests_path %>
</div>

app/views/reservation_guests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservation guests</h1>

<div id="reservation_guests">
  <% @reservation_guests.each do |reservation_guest| %>
    <%= render reservation_guest %>
    <p>
      <%= link_to "Show this reservation guest", reservation_guest %>
    </p>
  <% end %>
</div>

<%= link_to "New reservation guest", new_reservation_guest_path %>

app/views/reservation_guests/new.html.erb
<h1>New reservation guest</h1>

<%= render "form", reservation_guest: @reservation_guest %>

<br>

<div>
  <%= link_to "Back to reservation guests", reservation_guests_path %>
</div>

app/views/reservation_guests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation_guest %>

<div>
  <%= link_to "Edit this reservation guest", edit_reservation_guest_path(@reservation_guest) %> |
  <%= link_to "Back to reservation guests", reservation_guests_path %>

  <%= button_to "Destroy this reservation guest", @reservation_guest, method: :delete %>
</div>